version: '3'
services:
  mongo:
    container_name: mongo_container
    image: "mongo:3.6.8-stretch"
    ports:
      - "27017:27017"
    networks:
      - happinessnetwork
    ulimits:
      nofile: 65536
      # memlock:
      #   soft: -1
      #   hard: 1
    volumes:
      - mongodata:/data/db
  teamservice:
    container_name: teamservice
    image: "awconstable/teamservice:latest"
    depends_on:
      - mongo
    networks:
      - happinessnetwork
    ports:
      - "8082:8080"
    environment:
      - spring_data_mongodb_host=mongo_container
      - spring_data_mongodb_port=27017
      - spring_data_mongodb_database=team
  mailhog:
    container_name: mailhog
    image: mailhog/mailhog
    networks:
      - happinessnetwork
    ports:
      - "1025:1025"
      - "8025:8025"
  prom:
    container_name: prometheus_container
    image: prom/prometheus
    ports:
      - "9090:9090"
    networks:
      - happinessnetwork
    volumes:
      - "/vagrant/prometheus.yml:/etc/prometheus/prometheus.yml"
volumes:
  mongodata:
networks:
  happinessnetwork:
